#!/bin/bash


function success() {
    prompt="$1"
    echo -e -n "\033[1;32m$prompt"
    echo -e -n '\033[0m'
    echo -e -n "\n"
}
function error() {
    prompt="$1"
    echo -e -n "\033[1;31m$prompt"
    echo -e -n '\033[0m'
    echo -e -n "\n"
}
function info() {
    prompt="$1"
    echo -e -n "\033[1;36m$prompt"
    echo -e -n '\033[0m'
    echo -e -n "\n"
}

info 'Killing Docker Containers..'
docker rm -f $(docker ps -a -q) &>/dev/null
success "OK"

info 'Building Docker Containers..'
docker-compose up -d

success "Ready!"